---
- name: Gather vlans facts from the device using ios_vlans
  cisco.ios.ios_vlans:
    state: "{{ vlan_config_state }}"
  when: vlan_config_state == 'gathered'

- name: VLAN configuration with state - "{{ vlan_config_state }}"
  cisco.ios.ios_vlans:
    config: "{{ vlan_configs | ansible.builtin.from_yaml }}"
    state: "{{ vlan_config_state }}"
  when: vlan_config_state != 'gathered'
...
