---
- name: Gather interfaces facts from the device using ios_l2_interfaces
  cisco.ios.ios_l2_interfaces:
    state: "{{ interface_config_state }}"
  when: interface_config_state == 'gathered'

- name: Interface configuration with state - "{{ interface_config_state }}"
  cisco.ios.ios_l2_interfaces:
    config: "{{ interface_configs | ansible.builtin.from_yaml }}"
    state: "{{ interface_config_state }}"
  when: interface_config_state != 'gathered'
...
